"""
Tests for matching module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import pytest
from pathlib import Path
from ap_move_light_to_data import matching
from ap_common.constants import (
    NORMALIZED_HEADER_FILENAME,
    NORMALIZED_HEADER_EXPOSURESECONDS,
)


class TestGetLightFrames:
    """Tests for get_light_frames function."""

    def test_returns_empty_dict_for_nonexistent_directory(self):
        """Non-existent directory returns empty dict."""
        result = matching.get_light_frames("/nonexistent", metadata_cache={})
        assert result == {}


class TestFindAllLightDirectories:
    """Tests for find_all_light_directories function."""

    def test_returns_empty_list_for_nonexistent_directory(self):
        """Non-existent directory returns empty list."""
        result = matching.find_all_light_directories("/nonexistent", metadata_cache={})
        assert result == []


class TestIsFileInsideTree:
    """Tests for is_file_inside_tree function."""

    def test_file_inside_tree_returns_true(self, tmp_path):
        """File inside tree returns True."""
        tree = tmp_path / "tree"
        tree.mkdir()
        file_path = tree / "subdir" / "file.fits"
        file_path.parent.mkdir()
        file_path.touch()

        assert matching.is_file_inside_tree(str(file_path), str(tree)) is True

    def test_file_outside_tree_returns_false(self, tmp_path):
        """File outside tree returns False."""
        tree = tmp_path / "tree"
        tree.mkdir()
        outside = tmp_path / "outside"
        outside.mkdir()
        file_path = outside / "file.fits"
        file_path.touch()

        assert matching.is_file_inside_tree(str(file_path), str(tree)) is False

    def test_file_in_parent_returns_false(self, tmp_path):
        """File in parent of tree returns False."""
        parent = tmp_path / "parent"
        parent.mkdir()
        tree = parent / "tree"
        tree.mkdir()
        file_path = parent / "file.fits"
        file_path.touch()

        assert matching.is_file_inside_tree(str(file_path), str(tree)) is False


class TestCheckCalibrationForLight:
    """Tests for check_calibration_for_light function."""

    def test_missing_all_calibration(self, tmp_path, mocker):
        """Light with no calibration returns incomplete."""
        # Mock all cache-based calibration searches to return empty
        mocker.patch(
            "ap_common.calibration.find_matching_darks_from_cache",
            return_value=[],
        )
        mocker.patch(
            "ap_common.calibration.find_matching_flats_from_cache",
            return_value=[],
        )
        mocker.patch(
            "ap_common.calibration.find_matching_bias_from_cache",
            return_value=[],
        )

        light_metadata = {
            "NORMALIZED_HEADER_TYPE": "Light",
            "NORMALIZED_HEADER_EXPOSURESECONDS": 60.0,
        }
        search_dirs = [str(tmp_path)]

        result = matching.check_calibration_for_light(
            light_metadata,
            search_dirs,
            metadata_cache={},
            allow_bias=False,
            debug=False,
            quiet=True,
        )

        assert result["has_darks"] is False
        assert result["has_flats"] is False
        assert result["is_complete"] is False
        assert "darks" in result["missing"]
        assert "flats" in result["missing"]

    def test_empty_search_dirs(self, tmp_path, mocker):
        """Empty search_dirs list results in incomplete."""
        mocker.patch(
            "ap_common.calibration.find_matching_darks_from_cache",
            return_value=[],
        )
        mocker.patch(
            "ap_common.calibration.find_matching_flats_from_cache",
            return_value=[],
        )
        mocker.patch(
            "ap_common.calibration.find_matching_bias_from_cache",
            return_value=[],
        )

        light_metadata = {
            "NORMALIZED_HEADER_TYPE": "Light",
            NORMALIZED_HEADER_EXPOSURESECONDS: 60.0,
        }
        search_dirs = []  # Empty

        result = matching.check_calibration_for_light(
            light_metadata,
            search_dirs,
            metadata_cache={},
            allow_bias=False,
            debug=False,
            quiet=True,
        )

        assert result["has_darks"] is False
        assert result["has_flats"] is False
        assert result["is_complete"] is False
        assert "darks" in result["missing"]
        assert "flats" in result["missing"]
