"""
Tests for config module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from ap_move_light_to_data import config


def test_keyword_constants_exist():
    """Verify all keyword constants are defined."""
    assert config.KEYWORD_TYPE == "type"
    assert config.KEYWORD_CAMERA == "camera"
    assert config.KEYWORD_SETTEMP == "settemp"
    assert config.KEYWORD_GAIN == "gain"
    assert config.KEYWORD_OFFSET == "offset"
    assert config.KEYWORD_READOUTMODE == "readoutmode"
    assert config.KEYWORD_EXPOSURESECONDS == "exposureseconds"
    assert config.KEYWORD_DATE == "date"
    assert config.KEYWORD_FILTER == "filter"


def test_type_constants():
    """Verify frame type constants match FITS header values."""
    assert config.TYPE_LIGHT == "LIGHT"
    assert config.TYPE_DARK == "DARK"
    assert config.TYPE_FLAT == "FLAT"
    assert config.TYPE_BIAS == "BIAS"


def test_dark_match_keywords():
    """Verify dark matching keywords include required fields."""
    required = [
        config.KEYWORD_CAMERA,
        config.KEYWORD_SETTEMP,
        config.KEYWORD_GAIN,
        config.KEYWORD_OFFSET,
        config.KEYWORD_READOUTMODE,
    ]
    for kw in required:
        assert kw in config.DARK_MATCH_KEYWORDS


def test_flat_match_keywords():
    """Verify flat matching keywords include filter."""
    assert config.KEYWORD_FILTER in config.FLAT_MATCH_KEYWORDS
    # Flats should also match on camera settings
    assert config.KEYWORD_CAMERA in config.FLAT_MATCH_KEYWORDS


def test_default_directories():
    """Verify default directory names."""
    assert config.DEFAULT_BLINK_DIR == "10_Blink"
    assert config.DEFAULT_DATA_DIR == "20_Data"


def test_supported_extensions():
    """Verify supported file extensions (regex patterns)."""
    assert r"\.fits$" in config.SUPPORTED_EXTENSIONS
    assert r"\.fit$" in config.SUPPORTED_EXTENSIONS
    assert r"\.xisf$" in config.SUPPORTED_EXTENSIONS
