"""
Tests for config module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from ap_move_light_to_data import config
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
    TYPE_LIGHT,
    TYPE_DARK,
    TYPE_FLAT,
    TYPE_BIAS,
)


def test_keyword_constants_exist():
    """Verify all keyword constants are defined in config."""
    assert config.NORMALIZED_HEADER_TYPE == "type"
    assert config.NORMALIZED_HEADER_CAMERA == "camera"
    assert config.NORMALIZED_HEADER_SETTEMP == "settemp"
    assert config.NORMALIZED_HEADER_GAIN == "gain"
    assert config.NORMALIZED_HEADER_OFFSET == "offset"
    assert config.NORMALIZED_HEADER_READOUTMODE == "readoutmode"
    assert config.NORMALIZED_HEADER_EXPOSURESECONDS == "exposureseconds"
    assert config.NORMALIZED_HEADER_FILTER == "filter"


def test_type_constants_from_ap_common():
    """Verify frame type constants are imported from ap-common."""
    assert TYPE_LIGHT == "LIGHT"
    assert TYPE_DARK == "DARK"
    assert TYPE_FLAT == "FLAT"
    assert TYPE_BIAS == "BIAS"


def test_dark_match_keywords():
    """Verify dark matching keywords include required fields."""
    required = [
        NORMALIZED_HEADER_CAMERA,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_READOUTMODE,
    ]
    for kw in required:
        assert kw in config.DARK_MATCH_KEYWORDS


def test_flat_match_keywords():
    """Verify flat matching keywords include filter."""
    assert NORMALIZED_HEADER_FILTER in config.FLAT_MATCH_KEYWORDS
    # Flats should also match on camera settings
    assert NORMALIZED_HEADER_CAMERA in config.FLAT_MATCH_KEYWORDS


def test_default_directories():
    """Verify default directory names."""
    assert config.DEFAULT_BLINK_DIR == "10_Blink"
    assert config.DEFAULT_DATA_DIR == "20_Data"


def test_supported_extensions():
    """Verify supported file extensions (regex patterns)."""
    assert r"\.fits$" in config.SUPPORTED_EXTENSIONS
    assert r"\.fit$" in config.SUPPORTED_EXTENSIONS
    assert r"\.xisf$" in config.SUPPORTED_EXTENSIONS
