"""
ap-move-lights-to-data: Move lights to data directory when calibration frames exist.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

__version__ = "0.1.0"

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
    TYPE_LIGHT,
    TYPE_DARK,
    TYPE_FLAT,
    TYPE_BIAS,
)

# Import module-specific config constants
from .config import (
    LIGHT_REQUIRED_KEYWORDS,
    DARK_MATCH_KEYWORDS,
    FLAT_MATCH_KEYWORDS,
    SUPPORTED_EXTENSIONS,
)

from .matching import (
    get_light_frames,
    find_all_light_directories,
    check_calibration_for_light,
    is_file_inside_tree,
)

from .move_lights_to_data import (
    build_search_dirs,
    is_group_complete_and_self_contained,
    filter_by_pattern,
    check_light_directories,
    find_calibration_directories,
    organize_into_movable_groups,
    process_light_directories,
    print_summary,
    main,
)

__all__ = [
    "__version__",
    # Config constants
    "NORMALIZED_HEADER_TYPE",
    "NORMALIZED_HEADER_CAMERA",
    "NORMALIZED_HEADER_SETTEMP",
    "NORMALIZED_HEADER_GAIN",
    "NORMALIZED_HEADER_OFFSET",
    "NORMALIZED_HEADER_READOUTMODE",
    "NORMALIZED_HEADER_EXPOSURESECONDS",
    "NORMALIZED_HEADER_DATE",
    "NORMALIZED_HEADER_FILTER",
    "TYPE_LIGHT",
    "TYPE_DARK",
    "TYPE_FLAT",
    "TYPE_BIAS",
    "LIGHT_REQUIRED_KEYWORDS",
    "DARK_MATCH_KEYWORDS",
    "FLAT_MATCH_KEYWORDS",
    "SUPPORTED_EXTENSIONS",
    # Matching functions
    "get_light_frames",
    "find_all_light_directories",
    "check_calibration_for_light",
    "is_file_inside_tree",
    # Main functions
    "build_search_dirs",
    "is_group_complete_and_self_contained",
    "filter_by_pattern",
    "check_light_directories",
    "find_calibration_directories",
    "organize_into_movable_groups",
    "process_light_directories",
    "print_summary",
    "main",
]
