"""
ap-move-lights-to-data: Move lights to data directory when calibration frames exist.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

__version__ = "0.1.0"

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
    TYPE_LIGHT,
    TYPE_DARK,
    TYPE_FLAT,
    TYPE_BIAS,
)

# Import module-specific config constants
from .config import (
    LIGHT_REQUIRED_KEYWORDS,
    DARK_MATCH_KEYWORDS,
    FLAT_MATCH_KEYWORDS,
    SUPPORTED_EXTENSIONS,
    SUPPORTED_EXTENSIONS_RAW,
)

from .matching import (
    get_frames_by_type,
    find_matching_darks,
    find_matching_flats,
    find_matching_bias,
    check_calibration_status,
    collect_calibration_frames,
)

from .move_lights_to_data import (
    find_light_directories,
    get_target_from_path,
    move_directory,
    process_light_directories,
    main,
)

__all__ = [
    "__version__",
    # Config constants
    "NORMALIZED_HEADER_TYPE",
    "NORMALIZED_HEADER_CAMERA",
    "NORMALIZED_HEADER_SETTEMP",
    "NORMALIZED_HEADER_GAIN",
    "NORMALIZED_HEADER_OFFSET",
    "NORMALIZED_HEADER_READOUTMODE",
    "NORMALIZED_HEADER_EXPOSURESECONDS",
    "NORMALIZED_HEADER_DATE",
    "NORMALIZED_HEADER_FILTER",
    "TYPE_LIGHT",
    "TYPE_DARK",
    "TYPE_FLAT",
    "TYPE_BIAS",
    "LIGHT_REQUIRED_KEYWORDS",
    "DARK_MATCH_KEYWORDS",
    "FLAT_MATCH_KEYWORDS",
    "SUPPORTED_EXTENSIONS",
    "SUPPORTED_EXTENSIONS_RAW",
    # Matching functions
    "get_frames_by_type",
    "find_matching_darks",
    "find_matching_flats",
    "find_matching_bias",
    "check_calibration_status",
    "collect_calibration_frames",
    # Main functions
    "find_light_directories",
    "get_target_from_path",
    "move_directory",
    "process_light_directories",
    "main",
]
