"""
Entry point for running as module: python -m ap_move_light_to_data

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from .move_lights_to_data import main

if __name__ == "__main__":
    main()
