"""
Configuration constants for ap-move-light-to-data.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
    DEFAULT_IMAGE_PATTERNS,
)

# Skip reason codes for structured error handling
SKIP_REASON_NONE = ""
SKIP_REASON_NO_LIGHTS = "no_lights"
SKIP_REASON_NO_DARKS = "no_darks"
SKIP_REASON_NO_FLATS = "no_flats"
SKIP_REASON_NO_BIAS = "no_bias"

# Required keywords for matching lights to calibration frames
LIGHT_REQUIRED_KEYWORDS = [
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
]

# Keywords for matching darks to lights (excluding exposure for flexibility)
DARK_MATCH_KEYWORDS = [
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
]

# Keywords for matching flats to lights
FLAT_MATCH_KEYWORDS = [
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_FILTER,
]

# Union of all keywords needed for any frame type matching
# Used as required_properties for metadata loading to ensure all files
# get enriched with actual FITS/XISF headers (not just filename metadata)
ALL_REQUIRED_KEYWORDS = list(
    set(LIGHT_REQUIRED_KEYWORDS + DARK_MATCH_KEYWORDS + FLAT_MATCH_KEYWORDS)
)

# Default path pattern to match accept directories
# Matches paths containing an "accept" directory component
DEFAULT_PATH_PATTERN = r".*[/\\]accept[/\\].*"

# Supported file extensions (regex patterns for file matching)
# Use ap-common's DEFAULT_IMAGE_PATTERNS for all supported image types
SUPPORTED_EXTENSIONS = DEFAULT_IMAGE_PATTERNS
