"""
Configuration constants for ap-move-light-to-data.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import logging

# Normalized keyword names (matching ap-common normalization)
KEYWORD_TYPE = "type"
KEYWORD_CAMERA = "camera"
KEYWORD_SETTEMP = "settemp"
KEYWORD_GAIN = "gain"
KEYWORD_OFFSET = "offset"
KEYWORD_READOUTMODE = "readoutmode"
KEYWORD_EXPOSURESECONDS = "exposureseconds"
KEYWORD_DATE = "date"
KEYWORD_FILTER = "filter"

# Frame types (match actual FITS header values)
TYPE_LIGHT = "LIGHT"
TYPE_DARK = "DARK"
TYPE_FLAT = "FLAT"
TYPE_BIAS = "BIAS"

# Skip reason codes for structured error handling
SKIP_REASON_NONE = ""
SKIP_REASON_NO_LIGHTS = "no_lights"
SKIP_REASON_NO_DARKS = "no_darks"
SKIP_REASON_NO_FLATS = "no_flats"
SKIP_REASON_NO_BIAS = "no_bias"

# Required keywords for matching lights to calibration frames
LIGHT_REQUIRED_KEYWORDS = [
    KEYWORD_TYPE,
    KEYWORD_CAMERA,
    KEYWORD_SETTEMP,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_READOUTMODE,
    KEYWORD_EXPOSURESECONDS,
    KEYWORD_FILTER,
]

# Keywords for matching darks to lights (excluding exposure for flexibility)
DARK_MATCH_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_SETTEMP,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_READOUTMODE,
]

# Keywords for matching flats to lights
FLAT_MATCH_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_SETTEMP,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_READOUTMODE,
    KEYWORD_FILTER,
]

# Default directory names
DEFAULT_BLINK_DIR = "10_Blink"
DEFAULT_DATA_DIR = "20_Data"

# Supported file extensions (regex patterns for file matching)
SUPPORTED_EXTENSIONS = [r"\.fits$", r"\.fit$", r"\.xisf$"]

# Supported file extensions (for direct extension checks without regex)
SUPPORTED_EXTENSIONS_RAW = ["fits", "fit", "xisf"]

# Logging configuration
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"


def setup_logging(debug: bool = False) -> logging.Logger:
    """
    Setup logging configuration for the application.

    Args:
        debug: Enable debug level logging

    Returns:
        Configured logger instance
    """
    logger = logging.getLogger("ap_move_light_to_data")
    logger.setLevel(logging.DEBUG if debug else logging.INFO)

    # Remove existing handlers to avoid duplicates
    logger.handlers.clear()

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG if debug else logging.INFO)
    formatter = logging.Formatter(LOG_FORMAT, LOG_DATE_FORMAT)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    return logger
