"""
Configuration constants for ap-move-light-to-data.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
)

# Skip reason codes for structured error handling
SKIP_REASON_NONE = ""
SKIP_REASON_NO_LIGHTS = "no_lights"
SKIP_REASON_NO_DARKS = "no_darks"
SKIP_REASON_NO_FLATS = "no_flats"
SKIP_REASON_NO_BIAS = "no_bias"

# Required keywords for matching lights to calibration frames
LIGHT_REQUIRED_KEYWORDS = [
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
]

# Keywords for matching darks to lights (excluding exposure for flexibility)
DARK_MATCH_KEYWORDS = [
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
]

# Keywords for matching flats to lights
FLAT_MATCH_KEYWORDS = [
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_FILTER,
]

# Default directory names
DEFAULT_BLINK_DIR = "10_Blink"
DEFAULT_DATA_DIR = "20_Data"

# Supported file extensions (regex patterns for file matching)
SUPPORTED_EXTENSIONS = [r"\.fits$", r"\.fit$", r"\.xisf$"]

# Supported file extensions (for direct extension checks without regex)
SUPPORTED_EXTENSIONS_RAW = ["fits", "fit", "xisf"]
